import IISUpravlyayushhaya_kompaniyaОрганизацияEController from '../i-i-s-upravlyayushhaya-kompaniya-организация-e';

var IISUpravlyayushhaya_kompaniyaОрганизацияENewController = IISUpravlyayushhaya_kompaniyaОрганизацияEController;
export default IISUpravlyayushhaya_kompaniyaОрганизацияENewController;
