import IISUpravlyayushhaya_kompaniyaКвитанцияEController from '../i-i-s-upravlyayushhaya-kompaniya-квитанция-e';

var IISUpravlyayushhaya_kompaniyaКвитанцияENewController = IISUpravlyayushhaya_kompaniyaКвитанцияEController;
export default IISUpravlyayushhaya_kompaniyaКвитанцияENewController;
