import IISUpravlyayushhaya_kompaniyaПерерасчетКУEController from '../i-i-s-upravlyayushhaya-kompaniya-перерасчет-к-у-e';

var IISUpravlyayushhaya_kompaniyaПерерасчетКУENewController = IISUpravlyayushhaya_kompaniyaПерерасчетКУEController;
export default IISUpravlyayushhaya_kompaniyaПерерасчетКУENewController;
