import IISUpravlyayushhaya_kompaniyaДолжностиEController from '../i-i-s-upravlyayushhaya-kompaniya-должности-e';

var IISUpravlyayushhaya_kompaniyaДолжностиENewController = IISUpravlyayushhaya_kompaniyaДолжностиEController;
export default IISUpravlyayushhaya_kompaniyaДолжностиENewController;
