//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Upravlyayushhaya_kompaniya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// База данных ЛС.
    /// </summary>
    // *** Start programmer edit section *** (БазаДанныхЛС CustomAttributes)

    // *** End programmer edit section *** (БазаДанныхЛС CustomAttributes)
    [AutoAltered()]
    [Caption("База данных лицевых счетов")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("БазаДанныхЛСE", new string[] {
            "Дата as \'Дата\'",
            "IDжильца as \'I dжильца\'"})]
    [View("БазаДанныхЛСL", new string[] {
            "Дата as \'Дата\'",
            "IDжильца as \'I dжильца\'"})]
    public class БазаДанныхЛС : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерЛицСчет;
        
        private int fДоляСобст;
        
        private System.DateTime fДатаФормЛС;
        
        private int fIDжильца;
        
        private System.DateTime fДата;
        
        private int fКолПрожив;
        
        private IIS.Upravlyayushhaya_kompaniya.Жилец fЖилец;
        
        // *** Start programmer edit section *** (БазаДанныхЛС CustomMembers)

        // *** End programmer edit section *** (БазаДанныхЛС CustomMembers)

        
        /// <summary>
        /// IDжильца.
        /// </summary>
        // *** Start programmer edit section *** (БазаДанныхЛС.IDжильца CustomAttributes)

        // *** End programmer edit section *** (БазаДанныхЛС.IDжильца CustomAttributes)
        public virtual int IDжильца
        {
            get
            {
                // *** Start programmer edit section *** (БазаДанныхЛС.IDжильца Get start)

                // *** End programmer edit section *** (БазаДанныхЛС.IDжильца Get start)
                int result = this.fIDжильца;
                // *** Start programmer edit section *** (БазаДанныхЛС.IDжильца Get end)

                // *** End programmer edit section *** (БазаДанныхЛС.IDжильца Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БазаДанныхЛС.IDжильца Set start)

                // *** End programmer edit section *** (БазаДанныхЛС.IDжильца Set start)
                this.fIDжильца = value;
                // *** Start programmer edit section *** (БазаДанныхЛС.IDжильца Set end)

                // *** End programmer edit section *** (БазаДанныхЛС.IDжильца Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (БазаДанныхЛС.Дата CustomAttributes)

        // *** End programmer edit section *** (БазаДанныхЛС.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (БазаДанныхЛС.Дата Get start)

                // *** End programmer edit section *** (БазаДанныхЛС.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (БазаДанныхЛС.Дата Get end)

                // *** End programmer edit section *** (БазаДанныхЛС.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БазаДанныхЛС.Дата Set start)

                // *** End programmer edit section *** (БазаДанныхЛС.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (БазаДанныхЛС.Дата Set end)

                // *** End programmer edit section *** (БазаДанныхЛС.Дата Set end)
            }
        }
        
        /// <summary>
        /// ДатаФормЛС.
        /// </summary>
        // *** Start programmer edit section *** (БазаДанныхЛС.ДатаФормЛС CustomAttributes)

        // *** End programmer edit section *** (БазаДанныхЛС.ДатаФормЛС CustomAttributes)
        public virtual System.DateTime ДатаФормЛС
        {
            get
            {
                // *** Start programmer edit section *** (БазаДанныхЛС.ДатаФормЛС Get start)

                // *** End programmer edit section *** (БазаДанныхЛС.ДатаФормЛС Get start)
                System.DateTime result = this.fДатаФормЛС;
                // *** Start programmer edit section *** (БазаДанныхЛС.ДатаФормЛС Get end)

                // *** End programmer edit section *** (БазаДанныхЛС.ДатаФормЛС Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БазаДанныхЛС.ДатаФормЛС Set start)

                // *** End programmer edit section *** (БазаДанныхЛС.ДатаФормЛС Set start)
                this.fДатаФормЛС = value;
                // *** Start programmer edit section *** (БазаДанныхЛС.ДатаФормЛС Set end)

                // *** End programmer edit section *** (БазаДанныхЛС.ДатаФормЛС Set end)
            }
        }
        
        /// <summary>
        /// ДоляСобст.
        /// </summary>
        // *** Start programmer edit section *** (БазаДанныхЛС.ДоляСобст CustomAttributes)

        // *** End programmer edit section *** (БазаДанныхЛС.ДоляСобст CustomAttributes)
        public virtual int ДоляСобст
        {
            get
            {
                // *** Start programmer edit section *** (БазаДанныхЛС.ДоляСобст Get start)

                // *** End programmer edit section *** (БазаДанныхЛС.ДоляСобст Get start)
                int result = this.fДоляСобст;
                // *** Start programmer edit section *** (БазаДанныхЛС.ДоляСобст Get end)

                // *** End programmer edit section *** (БазаДанныхЛС.ДоляСобст Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БазаДанныхЛС.ДоляСобст Set start)

                // *** End programmer edit section *** (БазаДанныхЛС.ДоляСобст Set start)
                this.fДоляСобст = value;
                // *** Start programmer edit section *** (БазаДанныхЛС.ДоляСобст Set end)

                // *** End programmer edit section *** (БазаДанныхЛС.ДоляСобст Set end)
            }
        }
        
        /// <summary>
        /// КолПрожив.
        /// </summary>
        // *** Start programmer edit section *** (БазаДанныхЛС.КолПрожив CustomAttributes)

        // *** End programmer edit section *** (БазаДанныхЛС.КолПрожив CustomAttributes)
        public virtual int КолПрожив
        {
            get
            {
                // *** Start programmer edit section *** (БазаДанныхЛС.КолПрожив Get start)

                // *** End programmer edit section *** (БазаДанныхЛС.КолПрожив Get start)
                int result = this.fКолПрожив;
                // *** Start programmer edit section *** (БазаДанныхЛС.КолПрожив Get end)

                // *** End programmer edit section *** (БазаДанныхЛС.КолПрожив Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БазаДанныхЛС.КолПрожив Set start)

                // *** End programmer edit section *** (БазаДанныхЛС.КолПрожив Set start)
                this.fКолПрожив = value;
                // *** Start programmer edit section *** (БазаДанныхЛС.КолПрожив Set end)

                // *** End programmer edit section *** (БазаДанныхЛС.КолПрожив Set end)
            }
        }
        
        /// <summary>
        /// НомерЛицСчет.
        /// </summary>
        // *** Start programmer edit section *** (БазаДанныхЛС.НомерЛицСчет CustomAttributes)

        // *** End programmer edit section *** (БазаДанныхЛС.НомерЛицСчет CustomAttributes)
        public virtual int НомерЛицСчет
        {
            get
            {
                // *** Start programmer edit section *** (БазаДанныхЛС.НомерЛицСчет Get start)

                // *** End programmer edit section *** (БазаДанныхЛС.НомерЛицСчет Get start)
                int result = this.fНомерЛицСчет;
                // *** Start programmer edit section *** (БазаДанныхЛС.НомерЛицСчет Get end)

                // *** End programmer edit section *** (БазаДанныхЛС.НомерЛицСчет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БазаДанныхЛС.НомерЛицСчет Set start)

                // *** End programmer edit section *** (БазаДанныхЛС.НомерЛицСчет Set start)
                this.fНомерЛицСчет = value;
                // *** Start programmer edit section *** (БазаДанныхЛС.НомерЛицСчет Set end)

                // *** End programmer edit section *** (БазаДанныхЛС.НомерЛицСчет Set end)
            }
        }
        
        /// <summary>
        /// База данных ЛС.
        /// </summary>
        // *** Start programmer edit section *** (БазаДанныхЛС.Жилец CustomAttributes)

        // *** End programmer edit section *** (БазаДанныхЛС.Жилец CustomAttributes)
        [PropertyStorage(new string[] {
                "Жилец"})]
        [NotNull()]
        public virtual IIS.Upravlyayushhaya_kompaniya.Жилец Жилец
        {
            get
            {
                // *** Start programmer edit section *** (БазаДанныхЛС.Жилец Get start)

                // *** End programmer edit section *** (БазаДанныхЛС.Жилец Get start)
                IIS.Upravlyayushhaya_kompaniya.Жилец result = this.fЖилец;
                // *** Start programmer edit section *** (БазаДанныхЛС.Жилец Get end)

                // *** End programmer edit section *** (БазаДанныхЛС.Жилец Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БазаДанныхЛС.Жилец Set start)

                // *** End programmer edit section *** (БазаДанныхЛС.Жилец Set start)
                this.fЖилец = value;
                // *** Start programmer edit section *** (БазаДанныхЛС.Жилец Set end)

                // *** End programmer edit section *** (БазаДанныхЛС.Жилец Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "БазаДанныхЛСE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View БазаДанныхЛСE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("БазаДанныхЛСE", typeof(IIS.Upravlyayushhaya_kompaniya.БазаДанныхЛС));
                }
            }
            
            /// <summary>
            /// "БазаДанныхЛСL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View БазаДанныхЛСL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("БазаДанныхЛСL", typeof(IIS.Upravlyayushhaya_kompaniya.БазаДанныхЛС));
                }
            }
        }
    }
}
