//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Upravlyayushhaya_kompaniya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Жилец.
    /// </summary>
    // *** Start programmer edit section *** (Жилец CustomAttributes)

    // *** End programmer edit section *** (Жилец CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЖилецE", new string[] {
            "IDжильца as \'I dжильца\'",
            "ФИО as \'ФИО\'",
            "Адрес as \'Адрес\'",
            "Телефон as \'Телефон\'"})]
    [View("ЖилецL", new string[] {
            "IDжильца as \'I dжильца\'",
            "ФИО as \'ФИО\'",
            "Адрес as \'Адрес\'",
            "Телефон as \'Телефон\'"})]
    public class Жилец : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private int fIDжильца;
        
        private string fАдрес;
        
        private int fТелефон;
        
        // *** Start programmer edit section *** (Жилец CustomMembers)

        // *** End programmer edit section *** (Жилец CustomMembers)

        
        /// <summary>
        /// IDжильца.
        /// </summary>
        // *** Start programmer edit section *** (Жилец.IDжильца CustomAttributes)

        // *** End programmer edit section *** (Жилец.IDжильца CustomAttributes)
        public virtual int IDжильца
        {
            get
            {
                // *** Start programmer edit section *** (Жилец.IDжильца Get start)

                // *** End programmer edit section *** (Жилец.IDжильца Get start)
                int result = this.fIDжильца;
                // *** Start programmer edit section *** (Жилец.IDжильца Get end)

                // *** End programmer edit section *** (Жилец.IDжильца Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Жилец.IDжильца Set start)

                // *** End programmer edit section *** (Жилец.IDжильца Set start)
                this.fIDжильца = value;
                // *** Start programmer edit section *** (Жилец.IDжильца Set end)

                // *** End programmer edit section *** (Жилец.IDжильца Set end)
            }
        }
        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (Жилец.Адрес CustomAttributes)

        // *** End programmer edit section *** (Жилец.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Жилец.Адрес Get start)

                // *** End programmer edit section *** (Жилец.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (Жилец.Адрес Get end)

                // *** End programmer edit section *** (Жилец.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Жилец.Адрес Set start)

                // *** End programmer edit section *** (Жилец.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Жилец.Адрес Set end)

                // *** End programmer edit section *** (Жилец.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (Жилец.Телефон CustomAttributes)

        // *** End programmer edit section *** (Жилец.Телефон CustomAttributes)
        public virtual int Телефон
        {
            get
            {
                // *** Start programmer edit section *** (Жилец.Телефон Get start)

                // *** End programmer edit section *** (Жилец.Телефон Get start)
                int result = this.fТелефон;
                // *** Start programmer edit section *** (Жилец.Телефон Get end)

                // *** End programmer edit section *** (Жилец.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Жилец.Телефон Set start)

                // *** End programmer edit section *** (Жилец.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (Жилец.Телефон Set end)

                // *** End programmer edit section *** (Жилец.Телефон Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Жилец.ФИО CustomAttributes)

        // *** End programmer edit section *** (Жилец.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Жилец.ФИО Get start)

                // *** End programmer edit section *** (Жилец.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Жилец.ФИО Get end)

                // *** End programmer edit section *** (Жилец.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Жилец.ФИО Set start)

                // *** End programmer edit section *** (Жилец.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Жилец.ФИО Set end)

                // *** End programmer edit section *** (Жилец.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЖилецE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЖилецE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЖилецE", typeof(IIS.Upravlyayushhaya_kompaniya.Жилец));
                }
            }
            
            /// <summary>
            /// "ЖилецL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЖилецL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЖилецL", typeof(IIS.Upravlyayushhaya_kompaniya.Жилец));
                }
            }
        }
    }
}
