//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Upravlyayushhaya_kompaniya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тариф.
    /// </summary>
    // *** Start programmer edit section *** (КоммуУслуги CustomAttributes)

    // *** End programmer edit section *** (КоммуУслуги CustomAttributes)
    [AutoAltered()]
    [Caption("Коммунальные услуги")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КоммуУслугиE", new string[] {
            "IDтарифа as \'I dтарифа\'",
            "Наименование as \'Наименование\'",
            "Стоимость as \'Стоимость\'"})]
    [View("КоммуУслугиL", new string[] {
            "IDтарифа as \'I dтарифа\'",
            "Наименование as \'Наименование\'",
            "Стоимость as \'Стоимость\'"})]
    [View("ТарифE", new string[] {
            "IDтарифа as \'I dтарифа\'",
            "Наименование as \'Наименование\'",
            "Стоимость as \'Стоимость\'"})]
    [View("ТарифL", new string[] {
            "IDтарифа as \'I dтарифа\'",
            "Наименование as \'Наименование\'",
            "Стоимость as \'Стоимость\'"})]
    public class КоммуУслуги : ICSSoft.STORMNET.DataObject
    {
        
        private int fIDтарифа;
        
        private string fНаименование;
        
        private int fСтоимость;
        
        // *** Start programmer edit section *** (КоммуУслуги CustomMembers)

        // *** End programmer edit section *** (КоммуУслуги CustomMembers)

        
        /// <summary>
        /// IDтарифа.
        /// </summary>
        // *** Start programmer edit section *** (КоммуУслуги.IDтарифа CustomAttributes)

        // *** End programmer edit section *** (КоммуУслуги.IDтарифа CustomAttributes)
        public virtual int IDтарифа
        {
            get
            {
                // *** Start programmer edit section *** (КоммуУслуги.IDтарифа Get start)

                // *** End programmer edit section *** (КоммуУслуги.IDтарифа Get start)
                int result = this.fIDтарифа;
                // *** Start programmer edit section *** (КоммуУслуги.IDтарифа Get end)

                // *** End programmer edit section *** (КоммуУслуги.IDтарифа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КоммуУслуги.IDтарифа Set start)

                // *** End programmer edit section *** (КоммуУслуги.IDтарифа Set start)
                this.fIDтарифа = value;
                // *** Start programmer edit section *** (КоммуУслуги.IDтарифа Set end)

                // *** End programmer edit section *** (КоммуУслуги.IDтарифа Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (КоммуУслуги.Наименование CustomAttributes)

        // *** End programmer edit section *** (КоммуУслуги.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (КоммуУслуги.Наименование Get start)

                // *** End programmer edit section *** (КоммуУслуги.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (КоммуУслуги.Наименование Get end)

                // *** End programmer edit section *** (КоммуУслуги.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КоммуУслуги.Наименование Set start)

                // *** End programmer edit section *** (КоммуУслуги.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (КоммуУслуги.Наименование Set end)

                // *** End programmer edit section *** (КоммуУслуги.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Стоимость.
        /// </summary>
        // *** Start programmer edit section *** (КоммуУслуги.Стоимость CustomAttributes)

        // *** End programmer edit section *** (КоммуУслуги.Стоимость CustomAttributes)
        public virtual int Стоимость
        {
            get
            {
                // *** Start programmer edit section *** (КоммуУслуги.Стоимость Get start)

                // *** End programmer edit section *** (КоммуУслуги.Стоимость Get start)
                int result = this.fСтоимость;
                // *** Start programmer edit section *** (КоммуУслуги.Стоимость Get end)

                // *** End programmer edit section *** (КоммуУслуги.Стоимость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КоммуУслуги.Стоимость Set start)

                // *** End programmer edit section *** (КоммуУслуги.Стоимость Set start)
                this.fСтоимость = value;
                // *** Start programmer edit section *** (КоммуУслуги.Стоимость Set end)

                // *** End programmer edit section *** (КоммуУслуги.Стоимость Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КоммуУслугиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КоммуУслугиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КоммуУслугиE", typeof(IIS.Upravlyayushhaya_kompaniya.КоммуУслуги));
                }
            }
            
            /// <summary>
            /// "КоммуУслугиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КоммуУслугиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КоммуУслугиL", typeof(IIS.Upravlyayushhaya_kompaniya.КоммуУслуги));
                }
            }
            
            /// <summary>
            /// "ТарифE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТарифE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТарифE", typeof(IIS.Upravlyayushhaya_kompaniya.КоммуУслуги));
                }
            }
            
            /// <summary>
            /// "ТарифL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТарифL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТарифL", typeof(IIS.Upravlyayushhaya_kompaniya.КоммуУслуги));
                }
            }
        }
    }
}
