//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Upravlyayushhaya_kompaniya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Организация.
    /// </summary>
    // *** Start programmer edit section *** (Организация CustomAttributes)

    // *** End programmer edit section *** (Организация CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОрганизацияE", new string[] {
            "IDорганизация as \'I dорганизация\'",
            "Наименование as \'Наименование\'",
            "Адрес as \'Адрес\'",
            "Телефон as \'Телефон\'",
            "Email as \'Email\'",
            "РасчетныйСчет as \'Расчетный счет\'",
            "Банк as \'Банк\'",
            "ИНН as \'ИНН\'",
            "БИК as \'БИК\'",
            "КПП as \'КПП\'",
            "КорреСчет as \'Корре счет\'"})]
    [View("ОрганизацияL", new string[] {
            "IDорганизация as \'I dорганизация\'",
            "Наименование as \'Наименование\'",
            "Адрес as \'Адрес\'",
            "Телефон as \'Телефон\'",
            "Email as \'Email\'",
            "РасчетныйСчет as \'Расчетный счет\'",
            "Банк as \'Банк\'",
            "ИНН as \'ИНН\'",
            "БИК as \'БИК\'",
            "КПП as \'КПП\'",
            "КорреСчет as \'Корре счет\'"})]
    public class Организация : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private int fIDорганизация;
        
        private string fАдрес;
        
        private string fEmail;
        
        private int fРасчетныйСчет;
        
        private int fТелефон;
        
        private string fБанк;
        
        private int fИНН;
        
        private int fБИК;
        
        private int fКПП;
        
        private int fКорреСчет;
        
        // *** Start programmer edit section *** (Организация CustomMembers)

        // *** End programmer edit section *** (Организация CustomMembers)

        
        /// <summary>
        /// Email.
        /// </summary>
        // *** Start programmer edit section *** (Организация.Email CustomAttributes)

        // *** End programmer edit section *** (Организация.Email CustomAttributes)
        [StrLen(255)]
        public virtual string Email
        {
            get
            {
                // *** Start programmer edit section *** (Организация.Email Get start)

                // *** End programmer edit section *** (Организация.Email Get start)
                string result = this.fEmail;
                // *** Start programmer edit section *** (Организация.Email Get end)

                // *** End programmer edit section *** (Организация.Email Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организация.Email Set start)

                // *** End programmer edit section *** (Организация.Email Set start)
                this.fEmail = value;
                // *** Start programmer edit section *** (Организация.Email Set end)

                // *** End programmer edit section *** (Организация.Email Set end)
            }
        }
        
        /// <summary>
        /// IDорганизация.
        /// </summary>
        // *** Start programmer edit section *** (Организация.IDорганизация CustomAttributes)

        // *** End programmer edit section *** (Организация.IDорганизация CustomAttributes)
        public virtual int IDорганизация
        {
            get
            {
                // *** Start programmer edit section *** (Организация.IDорганизация Get start)

                // *** End programmer edit section *** (Организация.IDорганизация Get start)
                int result = this.fIDорганизация;
                // *** Start programmer edit section *** (Организация.IDорганизация Get end)

                // *** End programmer edit section *** (Организация.IDорганизация Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организация.IDорганизация Set start)

                // *** End programmer edit section *** (Организация.IDорганизация Set start)
                this.fIDорганизация = value;
                // *** Start programmer edit section *** (Организация.IDорганизация Set end)

                // *** End programmer edit section *** (Организация.IDорганизация Set end)
            }
        }
        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (Организация.Адрес CustomAttributes)

        // *** End programmer edit section *** (Организация.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Организация.Адрес Get start)

                // *** End programmer edit section *** (Организация.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (Организация.Адрес Get end)

                // *** End programmer edit section *** (Организация.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организация.Адрес Set start)

                // *** End programmer edit section *** (Организация.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Организация.Адрес Set end)

                // *** End programmer edit section *** (Организация.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Банк.
        /// </summary>
        // *** Start programmer edit section *** (Организация.Банк CustomAttributes)

        // *** End programmer edit section *** (Организация.Банк CustomAttributes)
        [StrLen(255)]
        public virtual string Банк
        {
            get
            {
                // *** Start programmer edit section *** (Организация.Банк Get start)

                // *** End programmer edit section *** (Организация.Банк Get start)
                string result = this.fБанк;
                // *** Start programmer edit section *** (Организация.Банк Get end)

                // *** End programmer edit section *** (Организация.Банк Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организация.Банк Set start)

                // *** End programmer edit section *** (Организация.Банк Set start)
                this.fБанк = value;
                // *** Start programmer edit section *** (Организация.Банк Set end)

                // *** End programmer edit section *** (Организация.Банк Set end)
            }
        }
        
        /// <summary>
        /// БИК.
        /// </summary>
        // *** Start programmer edit section *** (Организация.БИК CustomAttributes)

        // *** End programmer edit section *** (Организация.БИК CustomAttributes)
        public virtual int БИК
        {
            get
            {
                // *** Start programmer edit section *** (Организация.БИК Get start)

                // *** End programmer edit section *** (Организация.БИК Get start)
                int result = this.fБИК;
                // *** Start programmer edit section *** (Организация.БИК Get end)

                // *** End programmer edit section *** (Организация.БИК Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организация.БИК Set start)

                // *** End programmer edit section *** (Организация.БИК Set start)
                this.fБИК = value;
                // *** Start programmer edit section *** (Организация.БИК Set end)

                // *** End programmer edit section *** (Организация.БИК Set end)
            }
        }
        
        /// <summary>
        /// ИНН.
        /// </summary>
        // *** Start programmer edit section *** (Организация.ИНН CustomAttributes)

        // *** End programmer edit section *** (Организация.ИНН CustomAttributes)
        public virtual int ИНН
        {
            get
            {
                // *** Start programmer edit section *** (Организация.ИНН Get start)

                // *** End programmer edit section *** (Организация.ИНН Get start)
                int result = this.fИНН;
                // *** Start programmer edit section *** (Организация.ИНН Get end)

                // *** End programmer edit section *** (Организация.ИНН Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организация.ИНН Set start)

                // *** End programmer edit section *** (Организация.ИНН Set start)
                this.fИНН = value;
                // *** Start programmer edit section *** (Организация.ИНН Set end)

                // *** End programmer edit section *** (Организация.ИНН Set end)
            }
        }
        
        /// <summary>
        /// КорреСчет.
        /// </summary>
        // *** Start programmer edit section *** (Организация.КорреСчет CustomAttributes)

        // *** End programmer edit section *** (Организация.КорреСчет CustomAttributes)
        public virtual int КорреСчет
        {
            get
            {
                // *** Start programmer edit section *** (Организация.КорреСчет Get start)

                // *** End programmer edit section *** (Организация.КорреСчет Get start)
                int result = this.fКорреСчет;
                // *** Start programmer edit section *** (Организация.КорреСчет Get end)

                // *** End programmer edit section *** (Организация.КорреСчет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организация.КорреСчет Set start)

                // *** End programmer edit section *** (Организация.КорреСчет Set start)
                this.fКорреСчет = value;
                // *** Start programmer edit section *** (Организация.КорреСчет Set end)

                // *** End programmer edit section *** (Организация.КорреСчет Set end)
            }
        }
        
        /// <summary>
        /// КПП.
        /// </summary>
        // *** Start programmer edit section *** (Организация.КПП CustomAttributes)

        // *** End programmer edit section *** (Организация.КПП CustomAttributes)
        public virtual int КПП
        {
            get
            {
                // *** Start programmer edit section *** (Организация.КПП Get start)

                // *** End programmer edit section *** (Организация.КПП Get start)
                int result = this.fКПП;
                // *** Start programmer edit section *** (Организация.КПП Get end)

                // *** End programmer edit section *** (Организация.КПП Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организация.КПП Set start)

                // *** End programmer edit section *** (Организация.КПП Set start)
                this.fКПП = value;
                // *** Start programmer edit section *** (Организация.КПП Set end)

                // *** End programmer edit section *** (Организация.КПП Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Организация.Наименование CustomAttributes)

        // *** End programmer edit section *** (Организация.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Организация.Наименование Get start)

                // *** End programmer edit section *** (Организация.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Организация.Наименование Get end)

                // *** End programmer edit section *** (Организация.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организация.Наименование Set start)

                // *** End programmer edit section *** (Организация.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Организация.Наименование Set end)

                // *** End programmer edit section *** (Организация.Наименование Set end)
            }
        }
        
        /// <summary>
        /// РасчетныйСчет.
        /// </summary>
        // *** Start programmer edit section *** (Организация.РасчетныйСчет CustomAttributes)

        // *** End programmer edit section *** (Организация.РасчетныйСчет CustomAttributes)
        public virtual int РасчетныйСчет
        {
            get
            {
                // *** Start programmer edit section *** (Организация.РасчетныйСчет Get start)

                // *** End programmer edit section *** (Организация.РасчетныйСчет Get start)
                int result = this.fРасчетныйСчет;
                // *** Start programmer edit section *** (Организация.РасчетныйСчет Get end)

                // *** End programmer edit section *** (Организация.РасчетныйСчет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организация.РасчетныйСчет Set start)

                // *** End programmer edit section *** (Организация.РасчетныйСчет Set start)
                this.fРасчетныйСчет = value;
                // *** Start programmer edit section *** (Организация.РасчетныйСчет Set end)

                // *** End programmer edit section *** (Организация.РасчетныйСчет Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (Организация.Телефон CustomAttributes)

        // *** End programmer edit section *** (Организация.Телефон CustomAttributes)
        public virtual int Телефон
        {
            get
            {
                // *** Start programmer edit section *** (Организация.Телефон Get start)

                // *** End programmer edit section *** (Организация.Телефон Get start)
                int result = this.fТелефон;
                // *** Start programmer edit section *** (Организация.Телефон Get end)

                // *** End programmer edit section *** (Организация.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организация.Телефон Set start)

                // *** End programmer edit section *** (Организация.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (Организация.Телефон Set end)

                // *** End programmer edit section *** (Организация.Телефон Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОрганизацияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОрганизацияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОрганизацияE", typeof(IIS.Upravlyayushhaya_kompaniya.Организация));
                }
            }
            
            /// <summary>
            /// "ОрганизацияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОрганизацияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОрганизацияL", typeof(IIS.Upravlyayushhaya_kompaniya.Организация));
                }
            }
        }
    }
}
