//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Upravlyayushhaya_kompaniya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Перерасчет КУ.
    /// </summary>
    // *** Start programmer edit section *** (ПерерасчетКУ CustomAttributes)

    // *** End programmer edit section *** (ПерерасчетКУ CustomAttributes)
    [AutoAltered()]
    [Caption("Перерасчет коммунальных услуг")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПерерасчетКУE", new string[] {
            "Номер as \'Номер\'",
            "IDжильца as \'I dжильца\'",
            "IDорганизация as \'I dорганизация\'",
            "IDсотрудника as \'I dсотрудника\'"})]
    [View("ПерерасчетКУL", new string[] {
            "Номер as \'Номер\'",
            "IDжильца as \'I dжильца\'",
            "IDорганизация as \'I dорганизация\'",
            "IDсотрудника as \'I dсотрудника\'"})]
    public class ПерерасчетКУ : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаОкон;
        
        private int fIDсотрудника;
        
        private int fIDжильца;
        
        private string fОсновПерер;
        
        private int fIDорганизация;
        
        private System.DateTime fДатаФорДок;
        
        private int fЧасовПерер;
        
        private int fНомер;
        
        private int fДнейПерер;
        
        private System.DateTime fДатаНач;
        
        private IIS.Upravlyayushhaya_kompaniya.Жилец fЖилец;
        
        private IIS.Upravlyayushhaya_kompaniya.Сотрудники fСотрудники;
        
        private IIS.Upravlyayushhaya_kompaniya.Организация fОрганизация;
        
        private IIS.Upravlyayushhaya_kompaniya.DetailArrayOfТЧПерерасчетаКУ fТЧПерерасчетаКУ;
        
        // *** Start programmer edit section *** (ПерерасчетКУ CustomMembers)

        // *** End programmer edit section *** (ПерерасчетКУ CustomMembers)

        
        /// <summary>
        /// IDжильца.
        /// </summary>
        // *** Start programmer edit section *** (ПерерасчетКУ.IDжильца CustomAttributes)

        // *** End programmer edit section *** (ПерерасчетКУ.IDжильца CustomAttributes)
        public virtual int IDжильца
        {
            get
            {
                // *** Start programmer edit section *** (ПерерасчетКУ.IDжильца Get start)

                // *** End programmer edit section *** (ПерерасчетКУ.IDжильца Get start)
                int result = this.fIDжильца;
                // *** Start programmer edit section *** (ПерерасчетКУ.IDжильца Get end)

                // *** End programmer edit section *** (ПерерасчетКУ.IDжильца Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПерерасчетКУ.IDжильца Set start)

                // *** End programmer edit section *** (ПерерасчетКУ.IDжильца Set start)
                this.fIDжильца = value;
                // *** Start programmer edit section *** (ПерерасчетКУ.IDжильца Set end)

                // *** End programmer edit section *** (ПерерасчетКУ.IDжильца Set end)
            }
        }
        
        /// <summary>
        /// IDорганизация.
        /// </summary>
        // *** Start programmer edit section *** (ПерерасчетКУ.IDорганизация CustomAttributes)

        // *** End programmer edit section *** (ПерерасчетКУ.IDорганизация CustomAttributes)
        public virtual int IDорганизация
        {
            get
            {
                // *** Start programmer edit section *** (ПерерасчетКУ.IDорганизация Get start)

                // *** End programmer edit section *** (ПерерасчетКУ.IDорганизация Get start)
                int result = this.fIDорганизация;
                // *** Start programmer edit section *** (ПерерасчетКУ.IDорганизация Get end)

                // *** End programmer edit section *** (ПерерасчетКУ.IDорганизация Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПерерасчетКУ.IDорганизация Set start)

                // *** End programmer edit section *** (ПерерасчетКУ.IDорганизация Set start)
                this.fIDорганизация = value;
                // *** Start programmer edit section *** (ПерерасчетКУ.IDорганизация Set end)

                // *** End programmer edit section *** (ПерерасчетКУ.IDорганизация Set end)
            }
        }
        
        /// <summary>
        /// IDсотрудника.
        /// </summary>
        // *** Start programmer edit section *** (ПерерасчетКУ.IDсотрудника CustomAttributes)

        // *** End programmer edit section *** (ПерерасчетКУ.IDсотрудника CustomAttributes)
        public virtual int IDсотрудника
        {
            get
            {
                // *** Start programmer edit section *** (ПерерасчетКУ.IDсотрудника Get start)

                // *** End programmer edit section *** (ПерерасчетКУ.IDсотрудника Get start)
                int result = this.fIDсотрудника;
                // *** Start programmer edit section *** (ПерерасчетКУ.IDсотрудника Get end)

                // *** End programmer edit section *** (ПерерасчетКУ.IDсотрудника Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПерерасчетКУ.IDсотрудника Set start)

                // *** End programmer edit section *** (ПерерасчетКУ.IDсотрудника Set start)
                this.fIDсотрудника = value;
                // *** Start programmer edit section *** (ПерерасчетКУ.IDсотрудника Set end)

                // *** End programmer edit section *** (ПерерасчетКУ.IDсотрудника Set end)
            }
        }
        
        /// <summary>
        /// ДатаНач.
        /// </summary>
        // *** Start programmer edit section *** (ПерерасчетКУ.ДатаНач CustomAttributes)

        // *** End programmer edit section *** (ПерерасчетКУ.ДатаНач CustomAttributes)
        public virtual System.DateTime ДатаНач
        {
            get
            {
                // *** Start programmer edit section *** (ПерерасчетКУ.ДатаНач Get start)

                // *** End programmer edit section *** (ПерерасчетКУ.ДатаНач Get start)
                System.DateTime result = this.fДатаНач;
                // *** Start programmer edit section *** (ПерерасчетКУ.ДатаНач Get end)

                // *** End programmer edit section *** (ПерерасчетКУ.ДатаНач Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПерерасчетКУ.ДатаНач Set start)

                // *** End programmer edit section *** (ПерерасчетКУ.ДатаНач Set start)
                this.fДатаНач = value;
                // *** Start programmer edit section *** (ПерерасчетКУ.ДатаНач Set end)

                // *** End programmer edit section *** (ПерерасчетКУ.ДатаНач Set end)
            }
        }
        
        /// <summary>
        /// ДатаОкон.
        /// </summary>
        // *** Start programmer edit section *** (ПерерасчетКУ.ДатаОкон CustomAttributes)

        // *** End programmer edit section *** (ПерерасчетКУ.ДатаОкон CustomAttributes)
        public virtual System.DateTime ДатаОкон
        {
            get
            {
                // *** Start programmer edit section *** (ПерерасчетКУ.ДатаОкон Get start)

                // *** End programmer edit section *** (ПерерасчетКУ.ДатаОкон Get start)
                System.DateTime result = this.fДатаОкон;
                // *** Start programmer edit section *** (ПерерасчетКУ.ДатаОкон Get end)

                // *** End programmer edit section *** (ПерерасчетКУ.ДатаОкон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПерерасчетКУ.ДатаОкон Set start)

                // *** End programmer edit section *** (ПерерасчетКУ.ДатаОкон Set start)
                this.fДатаОкон = value;
                // *** Start programmer edit section *** (ПерерасчетКУ.ДатаОкон Set end)

                // *** End programmer edit section *** (ПерерасчетКУ.ДатаОкон Set end)
            }
        }
        
        /// <summary>
        /// ДатаФорДок.
        /// </summary>
        // *** Start programmer edit section *** (ПерерасчетКУ.ДатаФорДок CustomAttributes)

        // *** End programmer edit section *** (ПерерасчетКУ.ДатаФорДок CustomAttributes)
        public virtual System.DateTime ДатаФорДок
        {
            get
            {
                // *** Start programmer edit section *** (ПерерасчетКУ.ДатаФорДок Get start)

                // *** End programmer edit section *** (ПерерасчетКУ.ДатаФорДок Get start)
                System.DateTime result = this.fДатаФорДок;
                // *** Start programmer edit section *** (ПерерасчетКУ.ДатаФорДок Get end)

                // *** End programmer edit section *** (ПерерасчетКУ.ДатаФорДок Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПерерасчетКУ.ДатаФорДок Set start)

                // *** End programmer edit section *** (ПерерасчетКУ.ДатаФорДок Set start)
                this.fДатаФорДок = value;
                // *** Start programmer edit section *** (ПерерасчетКУ.ДатаФорДок Set end)

                // *** End programmer edit section *** (ПерерасчетКУ.ДатаФорДок Set end)
            }
        }
        
        /// <summary>
        /// ДнейПерер.
        /// </summary>
        // *** Start programmer edit section *** (ПерерасчетКУ.ДнейПерер CustomAttributes)

        // *** End programmer edit section *** (ПерерасчетКУ.ДнейПерер CustomAttributes)
        public virtual int ДнейПерер
        {
            get
            {
                // *** Start programmer edit section *** (ПерерасчетКУ.ДнейПерер Get start)

                // *** End programmer edit section *** (ПерерасчетКУ.ДнейПерер Get start)
                int result = this.fДнейПерер;
                // *** Start programmer edit section *** (ПерерасчетКУ.ДнейПерер Get end)

                // *** End programmer edit section *** (ПерерасчетКУ.ДнейПерер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПерерасчетКУ.ДнейПерер Set start)

                // *** End programmer edit section *** (ПерерасчетКУ.ДнейПерер Set start)
                this.fДнейПерер = value;
                // *** Start programmer edit section *** (ПерерасчетКУ.ДнейПерер Set end)

                // *** End programmer edit section *** (ПерерасчетКУ.ДнейПерер Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (ПерерасчетКУ.Номер CustomAttributes)

        // *** End programmer edit section *** (ПерерасчетКУ.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (ПерерасчетКУ.Номер Get start)

                // *** End programmer edit section *** (ПерерасчетКУ.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (ПерерасчетКУ.Номер Get end)

                // *** End programmer edit section *** (ПерерасчетКУ.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПерерасчетКУ.Номер Set start)

                // *** End programmer edit section *** (ПерерасчетКУ.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (ПерерасчетКУ.Номер Set end)

                // *** End programmer edit section *** (ПерерасчетКУ.Номер Set end)
            }
        }
        
        /// <summary>
        /// ОсновПерер.
        /// </summary>
        // *** Start programmer edit section *** (ПерерасчетКУ.ОсновПерер CustomAttributes)

        // *** End programmer edit section *** (ПерерасчетКУ.ОсновПерер CustomAttributes)
        [StrLen(255)]
        public virtual string ОсновПерер
        {
            get
            {
                // *** Start programmer edit section *** (ПерерасчетКУ.ОсновПерер Get start)

                // *** End programmer edit section *** (ПерерасчетКУ.ОсновПерер Get start)
                string result = this.fОсновПерер;
                // *** Start programmer edit section *** (ПерерасчетКУ.ОсновПерер Get end)

                // *** End programmer edit section *** (ПерерасчетКУ.ОсновПерер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПерерасчетКУ.ОсновПерер Set start)

                // *** End programmer edit section *** (ПерерасчетКУ.ОсновПерер Set start)
                this.fОсновПерер = value;
                // *** Start programmer edit section *** (ПерерасчетКУ.ОсновПерер Set end)

                // *** End programmer edit section *** (ПерерасчетКУ.ОсновПерер Set end)
            }
        }
        
        /// <summary>
        /// ЧасовПерер.
        /// </summary>
        // *** Start programmer edit section *** (ПерерасчетКУ.ЧасовПерер CustomAttributes)

        // *** End programmer edit section *** (ПерерасчетКУ.ЧасовПерер CustomAttributes)
        public virtual int ЧасовПерер
        {
            get
            {
                // *** Start programmer edit section *** (ПерерасчетКУ.ЧасовПерер Get start)

                // *** End programmer edit section *** (ПерерасчетКУ.ЧасовПерер Get start)
                int result = this.fЧасовПерер;
                // *** Start programmer edit section *** (ПерерасчетКУ.ЧасовПерер Get end)

                // *** End programmer edit section *** (ПерерасчетКУ.ЧасовПерер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПерерасчетКУ.ЧасовПерер Set start)

                // *** End programmer edit section *** (ПерерасчетКУ.ЧасовПерер Set start)
                this.fЧасовПерер = value;
                // *** Start programmer edit section *** (ПерерасчетКУ.ЧасовПерер Set end)

                // *** End programmer edit section *** (ПерерасчетКУ.ЧасовПерер Set end)
            }
        }
        
        /// <summary>
        /// Перерасчет КУ.
        /// </summary>
        // *** Start programmer edit section *** (ПерерасчетКУ.Жилец CustomAttributes)

        // *** End programmer edit section *** (ПерерасчетКУ.Жилец CustomAttributes)
        [PropertyStorage(new string[] {
                "Жилец"})]
        [NotNull()]
        public virtual IIS.Upravlyayushhaya_kompaniya.Жилец Жилец
        {
            get
            {
                // *** Start programmer edit section *** (ПерерасчетКУ.Жилец Get start)

                // *** End programmer edit section *** (ПерерасчетКУ.Жилец Get start)
                IIS.Upravlyayushhaya_kompaniya.Жилец result = this.fЖилец;
                // *** Start programmer edit section *** (ПерерасчетКУ.Жилец Get end)

                // *** End programmer edit section *** (ПерерасчетКУ.Жилец Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПерерасчетКУ.Жилец Set start)

                // *** End programmer edit section *** (ПерерасчетКУ.Жилец Set start)
                this.fЖилец = value;
                // *** Start programmer edit section *** (ПерерасчетКУ.Жилец Set end)

                // *** End programmer edit section *** (ПерерасчетКУ.Жилец Set end)
            }
        }
        
        /// <summary>
        /// Перерасчет КУ.
        /// </summary>
        // *** Start programmer edit section *** (ПерерасчетКУ.Организация CustomAttributes)

        // *** End programmer edit section *** (ПерерасчетКУ.Организация CustomAttributes)
        [PropertyStorage(new string[] {
                "Организация"})]
        [NotNull()]
        public virtual IIS.Upravlyayushhaya_kompaniya.Организация Организация
        {
            get
            {
                // *** Start programmer edit section *** (ПерерасчетКУ.Организация Get start)

                // *** End programmer edit section *** (ПерерасчетКУ.Организация Get start)
                IIS.Upravlyayushhaya_kompaniya.Организация result = this.fОрганизация;
                // *** Start programmer edit section *** (ПерерасчетКУ.Организация Get end)

                // *** End programmer edit section *** (ПерерасчетКУ.Организация Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПерерасчетКУ.Организация Set start)

                // *** End programmer edit section *** (ПерерасчетКУ.Организация Set start)
                this.fОрганизация = value;
                // *** Start programmer edit section *** (ПерерасчетКУ.Организация Set end)

                // *** End programmer edit section *** (ПерерасчетКУ.Организация Set end)
            }
        }
        
        /// <summary>
        /// Перерасчет КУ.
        /// </summary>
        // *** Start programmer edit section *** (ПерерасчетКУ.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ПерерасчетКУ.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Upravlyayushhaya_kompaniya.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ПерерасчетКУ.Сотрудники Get start)

                // *** End programmer edit section *** (ПерерасчетКУ.Сотрудники Get start)
                IIS.Upravlyayushhaya_kompaniya.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ПерерасчетКУ.Сотрудники Get end)

                // *** End programmer edit section *** (ПерерасчетКУ.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПерерасчетКУ.Сотрудники Set start)

                // *** End programmer edit section *** (ПерерасчетКУ.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ПерерасчетКУ.Сотрудники Set end)

                // *** End programmer edit section *** (ПерерасчетКУ.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Перерасчет КУ.
        /// </summary>
        // *** Start programmer edit section *** (ПерерасчетКУ.ТЧПерерасчетаКУ CustomAttributes)

        // *** End programmer edit section *** (ПерерасчетКУ.ТЧПерерасчетаКУ CustomAttributes)
        public virtual IIS.Upravlyayushhaya_kompaniya.DetailArrayOfТЧПерерасчетаКУ ТЧПерерасчетаКУ
        {
            get
            {
                // *** Start programmer edit section *** (ПерерасчетКУ.ТЧПерерасчетаКУ Get start)

                // *** End programmer edit section *** (ПерерасчетКУ.ТЧПерерасчетаКУ Get start)
                if ((this.fТЧПерерасчетаКУ == null))
                {
                    this.fТЧПерерасчетаКУ = new IIS.Upravlyayushhaya_kompaniya.DetailArrayOfТЧПерерасчетаКУ(this);
                }
                IIS.Upravlyayushhaya_kompaniya.DetailArrayOfТЧПерерасчетаКУ result = this.fТЧПерерасчетаКУ;
                // *** Start programmer edit section *** (ПерерасчетКУ.ТЧПерерасчетаКУ Get end)

                // *** End programmer edit section *** (ПерерасчетКУ.ТЧПерерасчетаКУ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПерерасчетКУ.ТЧПерерасчетаКУ Set start)

                // *** End programmer edit section *** (ПерерасчетКУ.ТЧПерерасчетаКУ Set start)
                this.fТЧПерерасчетаКУ = value;
                // *** Start programmer edit section *** (ПерерасчетКУ.ТЧПерерасчетаКУ Set end)

                // *** End programmer edit section *** (ПерерасчетКУ.ТЧПерерасчетаКУ Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПерерасчетКУE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПерерасчетКУE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПерерасчетКУE", typeof(IIS.Upravlyayushhaya_kompaniya.ПерерасчетКУ));
                }
            }
            
            /// <summary>
            /// "ПерерасчетКУL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПерерасчетКУL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПерерасчетКУL", typeof(IIS.Upravlyayushhaya_kompaniya.ПерерасчетКУ));
                }
            }
        }
    }
}
