//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Upravlyayushhaya_kompaniya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотрудники.
    /// </summary>
    // *** Start programmer edit section *** (Сотрудники CustomAttributes)

    // *** End programmer edit section *** (Сотрудники CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СотрудникиE", new string[] {
            "IDсотрудника as \'I dсотрудника\'",
            "IDдолжности as \'I dдолжности\'",
            "Телефон as \'Телефон\'",
            "ФИО as \'ФИО\'",
            "Email as \'Email\'",
            "Адрес as \'Адрес\'"})]
    [View("СотрудникиL", new string[] {
            "IDсотрудника as \'I dсотрудника\'",
            "IDдолжности as \'I dдолжности\'",
            "Телефон as \'Телефон\'",
            "ФИО as \'ФИО\'",
            "Email as \'Email\'",
            "Адрес as \'Адрес\'"})]
    public class Сотрудники : ICSSoft.STORMNET.DataObject
    {
        
        private int fIDдолжности;
        
        private int fIDсотрудника;
        
        private int fТелефон;
        
        private string fФИО;
        
        private string fEmail;
        
        private string fАдрес;
        
        private IIS.Upravlyayushhaya_kompaniya.Должности fДолжности;
        
        // *** Start programmer edit section *** (Сотрудники CustomMembers)

        // *** End programmer edit section *** (Сотрудники CustomMembers)

        
        /// <summary>
        /// Email.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Email CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Email CustomAttributes)
        [StrLen(255)]
        public virtual string Email
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Email Get start)

                // *** End programmer edit section *** (Сотрудники.Email Get start)
                string result = this.fEmail;
                // *** Start programmer edit section *** (Сотрудники.Email Get end)

                // *** End programmer edit section *** (Сотрудники.Email Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Email Set start)

                // *** End programmer edit section *** (Сотрудники.Email Set start)
                this.fEmail = value;
                // *** Start programmer edit section *** (Сотрудники.Email Set end)

                // *** End programmer edit section *** (Сотрудники.Email Set end)
            }
        }
        
        /// <summary>
        /// IDдолжности.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.IDдолжности CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.IDдолжности CustomAttributes)
        public virtual int IDдолжности
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.IDдолжности Get start)

                // *** End programmer edit section *** (Сотрудники.IDдолжности Get start)
                int result = this.fIDдолжности;
                // *** Start programmer edit section *** (Сотрудники.IDдолжности Get end)

                // *** End programmer edit section *** (Сотрудники.IDдолжности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.IDдолжности Set start)

                // *** End programmer edit section *** (Сотрудники.IDдолжности Set start)
                this.fIDдолжности = value;
                // *** Start programmer edit section *** (Сотрудники.IDдолжности Set end)

                // *** End programmer edit section *** (Сотрудники.IDдолжности Set end)
            }
        }
        
        /// <summary>
        /// IDсотрудника.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.IDсотрудника CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.IDсотрудника CustomAttributes)
        public virtual int IDсотрудника
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.IDсотрудника Get start)

                // *** End programmer edit section *** (Сотрудники.IDсотрудника Get start)
                int result = this.fIDсотрудника;
                // *** Start programmer edit section *** (Сотрудники.IDсотрудника Get end)

                // *** End programmer edit section *** (Сотрудники.IDсотрудника Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.IDсотрудника Set start)

                // *** End programmer edit section *** (Сотрудники.IDсотрудника Set start)
                this.fIDсотрудника = value;
                // *** Start programmer edit section *** (Сотрудники.IDсотрудника Set end)

                // *** End programmer edit section *** (Сотрудники.IDсотрудника Set end)
            }
        }
        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Адрес CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Адрес Get start)

                // *** End programmer edit section *** (Сотрудники.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (Сотрудники.Адрес Get end)

                // *** End programmer edit section *** (Сотрудники.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Адрес Set start)

                // *** End programmer edit section *** (Сотрудники.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Сотрудники.Адрес Set end)

                // *** End programmer edit section *** (Сотрудники.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Телефон CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Телефон CustomAttributes)
        public virtual int Телефон
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Телефон Get start)

                // *** End programmer edit section *** (Сотрудники.Телефон Get start)
                int result = this.fТелефон;
                // *** Start programmer edit section *** (Сотрудники.Телефон Get end)

                // *** End programmer edit section *** (Сотрудники.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Телефон Set start)

                // *** End programmer edit section *** (Сотрудники.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (Сотрудники.Телефон Set end)

                // *** End programmer edit section *** (Сотрудники.Телефон Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.ФИО CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.ФИО Get start)

                // *** End programmer edit section *** (Сотрудники.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Сотрудники.ФИО Get end)

                // *** End programmer edit section *** (Сотрудники.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.ФИО Set start)

                // *** End programmer edit section *** (Сотрудники.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Сотрудники.ФИО Set end)

                // *** End programmer edit section *** (Сотрудники.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Сотрудники.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Должности CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Должности CustomAttributes)
        [PropertyStorage(new string[] {
                "Должности"})]
        [NotNull()]
        public virtual IIS.Upravlyayushhaya_kompaniya.Должности Должности
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Должности Get start)

                // *** End programmer edit section *** (Сотрудники.Должности Get start)
                IIS.Upravlyayushhaya_kompaniya.Должности result = this.fДолжности;
                // *** Start programmer edit section *** (Сотрудники.Должности Get end)

                // *** End programmer edit section *** (Сотрудники.Должности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Должности Set start)

                // *** End programmer edit section *** (Сотрудники.Должности Set start)
                this.fДолжности = value;
                // *** Start programmer edit section *** (Сотрудники.Должности Set end)

                // *** End programmer edit section *** (Сотрудники.Должности Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СотрудникиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиE", typeof(IIS.Upravlyayushhaya_kompaniya.Сотрудники));
                }
            }
            
            /// <summary>
            /// "СотрудникиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиL", typeof(IIS.Upravlyayushhaya_kompaniya.Сотрудники));
                }
            }
        }
    }
}
