//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Upravlyayushhaya_kompaniya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т чквитанции.
    /// </summary>
    // *** Start programmer edit section *** (ТЧквитанции CustomAttributes)

    // *** End programmer edit section *** (ТЧквитанции CustomAttributes)
    [AutoAltered()]
    [Caption("Табличная часть квитанции")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧквитанцииE", new string[] {
            "Услуга as \'Услуга\'",
            "ОбъемКУ as \'Объем КУ\'",
            "IDтарифа as \'I dтарифа\'"})]
    public class ТЧквитанции : ICSSoft.STORMNET.DataObject
    {
        
        private string fУслуга;
        
        private int fОбъемКУ;
        
        private int fИтогоКОплЗаРП;
        
        private int fIDтарифа;
        
        private int fРазмПлатЗаКУ;
        
        private int fВсегоНачисЗаРП;
        
        private IIS.Upravlyayushhaya_kompaniya.КоммуУслуги fКоммуУслуги;
        
        private IIS.Upravlyayushhaya_kompaniya.Квитанция fКвитанция;
        
        // *** Start programmer edit section *** (ТЧквитанции CustomMembers)

        // *** End programmer edit section *** (ТЧквитанции CustomMembers)

        
        /// <summary>
        /// IDтарифа.
        /// </summary>
        // *** Start programmer edit section *** (ТЧквитанции.IDтарифа CustomAttributes)

        // *** End programmer edit section *** (ТЧквитанции.IDтарифа CustomAttributes)
        public virtual int IDтарифа
        {
            get
            {
                // *** Start programmer edit section *** (ТЧквитанции.IDтарифа Get start)

                // *** End programmer edit section *** (ТЧквитанции.IDтарифа Get start)
                int result = this.fIDтарифа;
                // *** Start programmer edit section *** (ТЧквитанции.IDтарифа Get end)

                // *** End programmer edit section *** (ТЧквитанции.IDтарифа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧквитанции.IDтарифа Set start)

                // *** End programmer edit section *** (ТЧквитанции.IDтарифа Set start)
                this.fIDтарифа = value;
                // *** Start programmer edit section *** (ТЧквитанции.IDтарифа Set end)

                // *** End programmer edit section *** (ТЧквитанции.IDтарифа Set end)
            }
        }
        
        /// <summary>
        /// ВсегоНачисЗаРП.
        /// </summary>
        // *** Start programmer edit section *** (ТЧквитанции.ВсегоНачисЗаРП CustomAttributes)

        // *** End programmer edit section *** (ТЧквитанции.ВсегоНачисЗаРП CustomAttributes)
        public virtual int ВсегоНачисЗаРП
        {
            get
            {
                // *** Start programmer edit section *** (ТЧквитанции.ВсегоНачисЗаРП Get start)

                // *** End programmer edit section *** (ТЧквитанции.ВсегоНачисЗаРП Get start)
                int result = this.fВсегоНачисЗаРП;
                // *** Start programmer edit section *** (ТЧквитанции.ВсегоНачисЗаРП Get end)

                // *** End programmer edit section *** (ТЧквитанции.ВсегоНачисЗаРП Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧквитанции.ВсегоНачисЗаРП Set start)

                // *** End programmer edit section *** (ТЧквитанции.ВсегоНачисЗаРП Set start)
                this.fВсегоНачисЗаРП = value;
                // *** Start programmer edit section *** (ТЧквитанции.ВсегоНачисЗаРП Set end)

                // *** End programmer edit section *** (ТЧквитанции.ВсегоНачисЗаРП Set end)
            }
        }
        
        /// <summary>
        /// ИтогоКОплЗаРП.
        /// </summary>
        // *** Start programmer edit section *** (ТЧквитанции.ИтогоКОплЗаРП CustomAttributes)

        // *** End programmer edit section *** (ТЧквитанции.ИтогоКОплЗаРП CustomAttributes)
        public virtual int ИтогоКОплЗаРП
        {
            get
            {
                // *** Start programmer edit section *** (ТЧквитанции.ИтогоКОплЗаРП Get start)

                // *** End programmer edit section *** (ТЧквитанции.ИтогоКОплЗаРП Get start)
                int result = this.fИтогоКОплЗаРП;
                // *** Start programmer edit section *** (ТЧквитанции.ИтогоКОплЗаРП Get end)

                // *** End programmer edit section *** (ТЧквитанции.ИтогоКОплЗаРП Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧквитанции.ИтогоКОплЗаРП Set start)

                // *** End programmer edit section *** (ТЧквитанции.ИтогоКОплЗаРП Set start)
                this.fИтогоКОплЗаРП = value;
                // *** Start programmer edit section *** (ТЧквитанции.ИтогоКОплЗаРП Set end)

                // *** End programmer edit section *** (ТЧквитанции.ИтогоКОплЗаРП Set end)
            }
        }
        
        /// <summary>
        /// ОбъемКУ.
        /// </summary>
        // *** Start programmer edit section *** (ТЧквитанции.ОбъемКУ CustomAttributes)

        // *** End programmer edit section *** (ТЧквитанции.ОбъемКУ CustomAttributes)
        public virtual int ОбъемКУ
        {
            get
            {
                // *** Start programmer edit section *** (ТЧквитанции.ОбъемКУ Get start)

                // *** End programmer edit section *** (ТЧквитанции.ОбъемКУ Get start)
                int result = this.fОбъемКУ;
                // *** Start programmer edit section *** (ТЧквитанции.ОбъемКУ Get end)

                // *** End programmer edit section *** (ТЧквитанции.ОбъемКУ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧквитанции.ОбъемКУ Set start)

                // *** End programmer edit section *** (ТЧквитанции.ОбъемКУ Set start)
                this.fОбъемКУ = value;
                // *** Start programmer edit section *** (ТЧквитанции.ОбъемКУ Set end)

                // *** End programmer edit section *** (ТЧквитанции.ОбъемКУ Set end)
            }
        }
        
        /// <summary>
        /// РазмПлатЗаКУ.
        /// </summary>
        // *** Start programmer edit section *** (ТЧквитанции.РазмПлатЗаКУ CustomAttributes)

        // *** End programmer edit section *** (ТЧквитанции.РазмПлатЗаКУ CustomAttributes)
        public virtual int РазмПлатЗаКУ
        {
            get
            {
                // *** Start programmer edit section *** (ТЧквитанции.РазмПлатЗаКУ Get start)

                // *** End programmer edit section *** (ТЧквитанции.РазмПлатЗаКУ Get start)
                int result = this.fРазмПлатЗаКУ;
                // *** Start programmer edit section *** (ТЧквитанции.РазмПлатЗаКУ Get end)

                // *** End programmer edit section *** (ТЧквитанции.РазмПлатЗаКУ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧквитанции.РазмПлатЗаКУ Set start)

                // *** End programmer edit section *** (ТЧквитанции.РазмПлатЗаКУ Set start)
                this.fРазмПлатЗаКУ = value;
                // *** Start programmer edit section *** (ТЧквитанции.РазмПлатЗаКУ Set end)

                // *** End programmer edit section *** (ТЧквитанции.РазмПлатЗаКУ Set end)
            }
        }
        
        /// <summary>
        /// Услуга.
        /// </summary>
        // *** Start programmer edit section *** (ТЧквитанции.Услуга CustomAttributes)

        // *** End programmer edit section *** (ТЧквитанции.Услуга CustomAttributes)
        [StrLen(255)]
        public virtual string Услуга
        {
            get
            {
                // *** Start programmer edit section *** (ТЧквитанции.Услуга Get start)

                // *** End programmer edit section *** (ТЧквитанции.Услуга Get start)
                string result = this.fУслуга;
                // *** Start programmer edit section *** (ТЧквитанции.Услуга Get end)

                // *** End programmer edit section *** (ТЧквитанции.Услуга Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧквитанции.Услуга Set start)

                // *** End programmer edit section *** (ТЧквитанции.Услуга Set start)
                this.fУслуга = value;
                // *** Start programmer edit section *** (ТЧквитанции.Услуга Set end)

                // *** End programmer edit section *** (ТЧквитанции.Услуга Set end)
            }
        }
        
        /// <summary>
        /// Т чквитанции.
        /// </summary>
        // *** Start programmer edit section *** (ТЧквитанции.КоммуУслуги CustomAttributes)

        // *** End programmer edit section *** (ТЧквитанции.КоммуУслуги CustomAttributes)
        [PropertyStorage(new string[] {
                "КоммуУслуги"})]
        [NotNull()]
        public virtual IIS.Upravlyayushhaya_kompaniya.КоммуУслуги КоммуУслуги
        {
            get
            {
                // *** Start programmer edit section *** (ТЧквитанции.КоммуУслуги Get start)

                // *** End programmer edit section *** (ТЧквитанции.КоммуУслуги Get start)
                IIS.Upravlyayushhaya_kompaniya.КоммуУслуги result = this.fКоммуУслуги;
                // *** Start programmer edit section *** (ТЧквитанции.КоммуУслуги Get end)

                // *** End programmer edit section *** (ТЧквитанции.КоммуУслуги Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧквитанции.КоммуУслуги Set start)

                // *** End programmer edit section *** (ТЧквитанции.КоммуУслуги Set start)
                this.fКоммуУслуги = value;
                // *** Start programmer edit section *** (ТЧквитанции.КоммуУслуги Set end)

                // *** End programmer edit section *** (ТЧквитанции.КоммуУслуги Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Upravlyayushhaya_kompaniya.Квитанция.
        /// </summary>
        // *** Start programmer edit section *** (ТЧквитанции.Квитанция CustomAttributes)

        // *** End programmer edit section *** (ТЧквитанции.Квитанция CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Квитанция"})]
        public virtual IIS.Upravlyayushhaya_kompaniya.Квитанция Квитанция
        {
            get
            {
                // *** Start programmer edit section *** (ТЧквитанции.Квитанция Get start)

                // *** End programmer edit section *** (ТЧквитанции.Квитанция Get start)
                IIS.Upravlyayushhaya_kompaniya.Квитанция result = this.fКвитанция;
                // *** Start programmer edit section *** (ТЧквитанции.Квитанция Get end)

                // *** End programmer edit section *** (ТЧквитанции.Квитанция Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧквитанции.Квитанция Set start)

                // *** End programmer edit section *** (ТЧквитанции.Квитанция Set start)
                this.fКвитанция = value;
                // *** Start programmer edit section *** (ТЧквитанции.Квитанция Set end)

                // *** End programmer edit section *** (ТЧквитанции.Квитанция Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧквитанцииE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧквитанцииE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧквитанцииE", typeof(IIS.Upravlyayushhaya_kompaniya.ТЧквитанции));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧквитанции.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧквитанции CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧквитанции CustomAttributes)
    public class DetailArrayOfТЧквитанции : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Upravlyayushhaya_kompaniya.DetailArrayOfТЧквитанции members)

        // *** End programmer edit section *** (IIS.Upravlyayushhaya_kompaniya.DetailArrayOfТЧквитанции members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧквитанции by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧквитанции.
        /// </summary>
        public DetailArrayOfТЧквитанции(IIS.Upravlyayushhaya_kompaniya.Квитанция fКвитанция) : 
                base(typeof(ТЧквитанции), ((ICSSoft.STORMNET.DataObject)(fКвитанция)))
        {
        }
        
        public IIS.Upravlyayushhaya_kompaniya.ТЧквитанции this[int index]
        {
            get
            {
                return ((IIS.Upravlyayushhaya_kompaniya.ТЧквитанции)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Upravlyayushhaya_kompaniya.ТЧквитанции dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
